### ISSUE TITLE
Entry point into the procedure Error

### ISSUE THREAD

**Issue by lisovskakateryna** [SagePtr/openserver-php-8.3#1]
I have a problem with php_curl.dll file. After starting the server, an error appears " Entry point into the procedure nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation not found in the library dll C:\ospanel\modules\php\php_8.3\ext\php_curl.dll "

**Comment by SagePtr** [comment]
You need to update your Apache, the old one is not fully compatible with PHP 8.2-8.3.
Here is my module: https://github.com/SagePtr/openserver-apache-2.4
Does it solve the problem?

**Comment by LuckyBro123** [comment]
у меня было то же самое, апдэйт апача решил проблему

**Comment by AsuRaHan** [comment]
![image](https://github.com/SagePtr/openserver-php-8.3/assets/6794500/08ff6707-9edd-47cf-823a-cfeea0d00c0e)
странная проблема. что то с курлом не так

**Comment by AsuRaHan** [comment]
> ![image](https://private-user-images.githubusercontent.com/6794500/317747020-08ff6707-9edd-47cf-823a-cfeea0d00c0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MzM3NjYsIm5iZiI6MTcxMTYzMzQ2NiwicGF0aCI6Ii82Nzk0NTAwLzMxNzc0NzAyMC0wOGZmNjcwNy05ZWRkLTQ3Y2YtODIzYS1jZmVlYTBkMDBjMGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMTM0NDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTAzZGViMDIyZmUyMzQwZjFlYzQzNDA5ODY0YWVkNjdjMWU0YThhNjlhN2VkYTllZTM3ZDAxODBjOTk2Nzg2NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.s1zHI_Q7lgyhfVaPoC2vqzZ_FebDuo9s7A5DbiZDq4o) странная проблема. что то с курлом не так

Решил проблему просто скачав с сайта виндовый релиз пыхи. и закинул курл длл сюда в папку пых83 и опенсервер запустился без проблем. если кому пригодится.

спасибо за релиз этого пакета для опенсервер. всетаки для винды оно лехче чем поднимать докер
