### ISSUE TITLE
невозможно включить отладку zend_extension = xdebug

### ISSUE THREAD

**Issue by LuckyBro123** [SagePtr/openserver-php-8.3#2]
Привет :)
Спасибо за апдэйт PHP для openserver 5 
Использую со вчера. Выявил проблему.

PHP 8.3
Раскомментировал в PHP_8.3_php.ini эти строки :
zend_extension = xdebug
xdebug.mode                     = develop,debug
xdebug.client_host              = "localhost"
xdebug.client_port              = 9003

После этого проект Laravel 10 не загружается, загрузка виснет. Процеcc httpd.exe хавает 10% - 45% процессора, раскручивает кулеры. И это длится долго, как минимум 1-2 минуты, далее я не ждал.

Если закомментировать zend_extension = xdebug, то нормально работает, но отладка не пашет. Если опять раскомментировать, опять виснет.

PHP 8.2 пока работает норм с отладкой. Вроде даже по сравнению с PHP 8.1.9 скорость загрузки страницы возросла с 900ms в режиме отладки до 600ms. Это так PHP 8.2.16 оптимизировали или в вашем апдейте чтото вырезано ?

PS
Забыл сказать, что Apache для 8.2-8.3 я скачал и применил в openserver.
И во время попыток решить проблему по всякому пробовал включать всё что можно

**Comment by LuckyBro123** [comment]
Забыл сказать, что Apache для 8.2-8.3 я скачал и применил в openserver. 
И во время попыток решить проблему по всякому пробовал включать всё что можно

**Comment by SagePtr** [comment]
У меня на 8.3.3 не воспроизводится проблема, отладка работает, но тестил на простеньком сайте, на тяжеловесных не пробовал.
Для PHP никакие оптимизации в этом модуле не производились, все файлы взяты с https://windows.php.net/ и https://xdebug.org/download, конфиг из OpenServer'овского PHP 8.1

**Comment by LuckyBro123** [comment]
Хмм. Я воодушевился, перезагрузился, применил танцы с бубном, но всё равно та же лажа. При запуске проекта размером 10кб вроде норм, а laravel-10 проекты не грузит при включенном zend_extension = xdebug. Тупо виснет загрузка, апач уходит в астрал на неопределённый срок. Уже минут 10 колбасится на 45% загрузки проца.
Винда вроде относительно чистая, недавно переставил.

Ну хотябы PHP 8.2.16 работает норм вроде бы. Спасибо за труды, бро :) Продлил жизнь openserver 543. 
Ато OS 6 beta без GUI - это путь самурая. Хочется без садомазо

**Comment by SagePtr** [comment]
Xdebug обновился до 3.3.2, проверьте теперь его производительность в связке с Апачем

[2024-04-15] — Xdebug 3.3.2
Fixed bugs
Fixed bug [#2216](https://bugs.xdebug.org/bug_view_page.php?bug_id=00002216): With PHP8.3 and Apache 2.4.58 error_reporting() causing Apache process to hang
Fixed bug [#2230](https://bugs.xdebug.org/bug_view_page.php?bug_id=00002230): Crash when xdebug and blackfire extensions are active
Fixed bug [#2233](https://bugs.xdebug.org/bug_view_page.php?bug_id=00002233): High and continuous Apache server CPU use
